language: node_js
node_js:
  - "5.4.0"
before_install:
  - npm install -g npm@3
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
before_script:
  - npm rebuild node-sass
script:
  - npm run lint
  - npm run build
