language: node_js
node_js:
  - "6"
before_install:
  - npm install -g npm@3
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
script:
  - npm run test
  - npm run build
